name: Run UI with Mochawesome

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select the browser to run the tests'
        required: true
        type: choice
        options:
          - chrome
          - edge
          - firefox
          - safari
          - electron

permissions:
  contents: write

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install WebKit dependencies (if selected)
        run: |
          if [ "${{ github.event.inputs.browser }}" = "safari" ]; then
            npx playwright install-deps webkit
            sudo apt-get install libavif16
          fi

      - name: Run API tests
        run: |
          BROWSER=${{ github.event.inputs.browser }}
          if [ "$BROWSER" = "safari" ]; then
            BROWSER="webkit"
          fi
          BROWSER=$BROWSER npm run test:ui-mochawesome

      - name: Merge Mochawesome reports
        run: npm run mochawesome:merge

      - name: Generate Mochawesome report
        run: npm run mochawesome:generate

      - name: List files in mochawesome-report
        run: ls -R mochawesome-report

      - name: List files in root
        run: ls -R .

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish Mochawesome report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          allow_empty_commit: true
          force_orphan: true

      - name: Wait for GitHub Pages to update
        run: sleep 10
