name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select the test type to run'
        required: true
        type: choice
        options:
          - ui
          - api

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
          cache: 'pnpm'

      - name: Install pnpm manually
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          # Ensure the installed pnpm is available
          echo "Adding pnpm to PATH"
          export PATH=$HOME/.local/share/pnpm/global/2/node_modules/.bin:$PATH
          echo "pnpm installation successful"
          pnpm --version
          # Persist PATH change for subsequent steps
          echo "export PATH=$HOME/.local/share/pnpm/global/2/node_modules/.bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Run selected tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "ui" ]; then
            pnpm run test:ui
          elif [ "${{ github.event.inputs.test_type }}" == "api" ]; then
            pnpm run test:api
          else
            echo "Unknown test type selected"
            exit 1
          fi
