name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select the test type to run'
        required: true
        type: choice
        options:
          - ui
          - api
      platform:
        description: 'Select the platform to run tests (only for UI tests)'
        required: false
        type: choice
        options:
          - linux
          - mac
          - windows
        default: linux

jobs:
  cypress-tests:
    runs-on: ${{ github.event.inputs.test_type == 'ui' && (github.event.inputs.platform == 'linux' && 'ubuntu-latest' || github.event.inputs.platform == 'mac' && 'macos-latest' || github.event.inputs.platform == 'windows' && 'windows-latest') || github.event.inputs.test_type == 'api' && 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run selected tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "ui" ]; then
            echo "Running UI tests on ${{ github.event.inputs.platform }}"
            npm run test:ui
          elif [ "${{ github.event.inputs.test_type }}" == "api" ]; then
            echo "Running API tests"
            npm run test:api
          else
            echo "Unknown test type selected"
            exit 1
          fi

      - name: Generate Allure report
        run: |
          npm run allure:generate
          npm run allure:open
